name: Publish library  

on:
  push:
     tags:        
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore src/TheChest.Core
    - name: Build project
      run: dotnet build src/TheChest.Core --no-restore --configuration Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ github.ref_name }}
        path: 'src/TheChest.Core/bin/Release'
        retention-days: 14
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: ${{ github.ref_name }}
          path: 'src/TheChest.Core/bin/Release'
      - name: Restore dependencies
        run: dotnet restore src/TheChest.Core
      - name: Pack library
        run: dotnet pack src/TheChest.Core --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Upload release attachment
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              `v${process.env.VERSION}`
            });
            const fileName = `TheChest.Core.${process.env.VERSION}.nupkg`;
            // Upload the release asset
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: fileName,
              data: await fs.readFileSync(fileName)
            });
