name: Publish library  

on:
  push:
    #branches:
    #  - "master"
     tags:        
      - "v*.*.**"
env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: $VERSION
        path: 'src/TheChest.Core/bin/Release'
        retention-days: 90
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}

          
